// GENERATED BY shadergraph — DO NOT EDIT.
//
// Edit the graph and recompile. Any change made here is lost the next time the
// graph is emitted.

#import bevy_pbr::forward_io::VertexOutput
#import bevy_pbr::pbr_types::{PbrInput, pbr_input_new}
#import bevy_pbr::pbr_functions::{apply_pbr_lighting, main_pass_post_lighting_processing}
#import bevy_pbr::mesh_view_bindings::view

// Always emitted, and named apart from the optional `sg_reject` snippet so the
// two never collide: the output node uses this to flatten the anisotropy
// tangent into the surface regardless of what the graph contains.
fn sg_reject_root(a: vec3<f32>, b: vec3<f32>) -> vec3<f32> {
    let denom = dot(b, b);
    if (denom < 1e-12) {
        return a;
    }
    return a - b * (dot(a, b) / denom);
}

struct SgSurface {
    base_color: vec4<f32>,
    metallic: f32,
    perceptual_roughness: f32,
    reflectance: f32,
    emissive: vec4<f32>,
    occlusion: f32,
    normal: vec3<f32>,
    anisotropy_strength: f32,
    anisotropy_tangent: vec3<f32>,
    alpha: f32,
}

struct SgParams {
    slots: array<vec4<f32>, 128>,
}
@group(#{MATERIAL_BIND_GROUP}) @binding(0) var<uniform> params: SgParams;

// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Fresnel reflectance.
//
// PROVENANCE: Schlick's approximation, from the published description in
// Christophe Schlick, "An Inexpensive BRDF Model for Physically-based
// Rendering" (Eurographics 1994). Textbook material; no code copied.

// Approximate the fraction of light reflected rather than transmitted at a
// dielectric interface, given the index of refraction and the viewing angle.
//
// `normal` and `view` are normalised defensively rather than trusted. They
// usually arrive already normalised, but a graph is free to wire anything into
// these sockets, and an un-normalised input silently biases `cos_theta` — which
// does not error, it just makes the rim term wrong in a way that reads as a
// material tuning problem rather than a graph bug.
//
// `cos_theta` is clamped to [0, 1] because back-facing fragments produce a
// negative dot product, and `pow(negative, 5.0)` is undefined in WGSL.
fn sg_fresnel(ior: f32, normal: vec3<f32>, view: vec3<f32>) -> f32 {
    // Reflectance at normal incidence, from the IOR ratio against air.
    let f0_root = (1.0 - ior) / (1.0 + ior);
    let f0 = f0_root * f0_root;

    let cos_theta = clamp(dot(normalize(normal), normalize(view)), 0.0, 1.0);

    // Schlick: F0 + (1 - F0)(1 - cos O)^5. The fifth power is what makes the
    // effect stay near F0 across most of the surface and climb steeply only at
    // grazing angles.
    return f0 + (1.0 - f0) * pow(1.0 - cos_theta, 5.0);
}

@fragment
fn fragment(in: VertexOutput, @builtin(front_facing) is_front: bool) -> @location(0) vec4<f32> {
    var pbr_input = pbr_input_new();

    let sg_position = in.world_position.xyz;
    let sg_normal = normalize(in.world_normal);
    let sg_view = normalize(view.world_position.xyz - in.world_position.xyz);

    pbr_input.frag_coord = in.position;
    pbr_input.world_position = in.world_position;
    pbr_input.world_normal = sg_normal;
    pbr_input.N = sg_normal;
    pbr_input.V = sg_view;
    // `clip_from_view[3][3] == 1.0` is the documented orthographic test.
    pbr_input.is_orthographic = view.clip_from_view[3][3] == 1.0;

    let n8_param = params.slots[0];
    let n10_param = params.slots[1].x;
    let n9_param = params.slots[2].x;
    let n4_param = params.slots[3].x;
    let n3_param = params.slots[4].x;
    let n5_math = (n3_param - n4_param);
    let n1_param = params.slots[5].x;
    let n2_fresnel = sg_fresnel(n1_param, sg_normal, sg_view);
    let n6_math = (n5_math * n2_fresnel);
    let n7_math = (n4_param + n6_math);
    let n11_surface = SgSurface(n8_param, n10_param, n9_param, 0.5, vec4<f32>(0.0, 0.0, 0.0, 1.0), 1.0, sg_normal, 0.0, vec3<f32>(0.0), n7_math);

    // --- surface properties ---
    pbr_input.material.base_color = n11_surface.base_color;
    pbr_input.material.base_color.a = n11_surface.alpha;
    pbr_input.material.metallic = n11_surface.metallic;
    pbr_input.material.perceptual_roughness = n11_surface.perceptual_roughness;
    pbr_input.material.reflectance = vec3<f32>(n11_surface.reflectance);
    pbr_input.material.emissive = n11_surface.emissive;
    pbr_input.diffuse_occlusion = vec3<f32>(n11_surface.occlusion);
    pbr_input.N = normalize(n11_surface.normal);

    // --- anisotropy ---
    pbr_input.anisotropy_strength = n11_surface.anisotropy_strength;
    let sg_aniso_t = sg_reject_root(n11_surface.anisotropy_tangent, pbr_input.N);
    if (dot(sg_aniso_t, sg_aniso_t) > 1e-12) {
        pbr_input.anisotropy_T = normalize(sg_aniso_t);
        pbr_input.anisotropy_B = normalize(cross(pbr_input.N, pbr_input.anisotropy_T));
    } else {
        pbr_input.anisotropy_strength = 0.0;
    }

    var out = apply_pbr_lighting(pbr_input);
    out = main_pass_post_lighting_processing(pbr_input, out);
    return out;
}
