// GENERATED BY shadergraph — DO NOT EDIT.
//
// Edit the graph and recompile. Any change made here is lost the next time the
// graph is emitted.

#import bevy_pbr::forward_io::VertexOutput
#import bevy_pbr::pbr_types::{PbrInput, pbr_input_new}
#import bevy_pbr::pbr_functions::{apply_pbr_lighting, main_pass_post_lighting_processing}
#import bevy_pbr::mesh_view_bindings::view

// Always emitted, and named apart from the optional `sg_reject` snippet so the
// two never collide: the output node uses this to flatten the anisotropy
// tangent into the surface regardless of what the graph contains.
fn sg_reject_root(a: vec3<f32>, b: vec3<f32>) -> vec3<f32> {
    let denom = dot(b, b);
    if (denom < 1e-12) {
        return a;
    }
    return a - b * (dot(a, b) / denom);
}

struct SgSurface {
    base_color: vec4<f32>,
    metallic: f32,
    perceptual_roughness: f32,
    reflectance: f32,
    emissive: vec4<f32>,
    occlusion: f32,
    normal: vec3<f32>,
    anisotropy_strength: f32,
    anisotropy_tangent: vec3<f32>,
    alpha: f32,
}

struct SgParams {
    slots: array<vec4<f32>, 128>,
}
@group(#{MATERIAL_BIND_GROUP}) @binding(0) var<uniform> params: SgParams;

// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Integer avalanche hashing for procedural noise.
//
// PROVENANCE: written from published descriptions of multiply-xorshift bit
// mixing. The xorshift/multiply/xorshift construction is the standard shape of
// an integer finaliser (the same form as SplitMix's finaliser and Wang's
// integer hash); the specific constants are the `lowbias32` pair from Chris
// Wellons' "Prospecting for Hash Functions", which the author released into the
// public domain. No shader code was copied from any renderer.

// Avalanche a single 32-bit integer.
//
// Three rounds, each an xor-with-right-shift followed by an odd-constant
// multiply. The xorshift moves entropy from the high bits (where multiplication
// concentrates it) back down into the low bits; the multiply then spreads it up
// again. Two full rounds plus a final xorshift is the minimum that passes
// avalanche testing — one round leaves the lowest bits visibly correlated,
// which in a Voronoi shows up as feature points aligning on faint grid lines.
fn sg_hash_u32(x_in: u32) -> u32 {
    var x = x_in;
    x ^= x >> 16u;
    x *= 0x7feb352du;
    x ^= x >> 15u;
    x *= 0x846ca68bu;
    x ^= x >> 16u;
    return x;
}

// Hash an integer lattice cell to three independent values in [0, 1).
//
// The cell coordinate arrives as a float because it came from `floor()`, and is
// bitcast through a signed integer rather than converted directly to `u32`:
// negative cells are ordinary (any surface at negative world coordinates lives
// in them), and `u32(-1.0)` is undefined in WGSL whereas `i32(-1.0)` is not.
//
// The three channels are decorrelated by re-hashing with distinct odd constants
// rather than by hashing three different tuples, which costs two extra rounds
// instead of two extra full hashes. The constants are the golden-ratio and
// SplitMix increments — any odd values with well-spread bits would do; these
// are conventional and easy to recognise.
fn sg_hash_cell(cell: vec3<f32>) -> vec3<f32> {
    let c = bitcast<vec3<u32>>(vec3<i32>(cell));

    // Fold the three axes into one value first, so that swapping two
    // coordinates gives an unrelated result. Hashing each axis separately and
    // summing would make the field symmetric about the diagonal — a subtle
    // artifact that is very visible on flat panels.
    let h0 = sg_hash_u32(c.x ^ sg_hash_u32(c.y ^ sg_hash_u32(c.z)));
    let h1 = sg_hash_u32(h0 ^ 0x9e3779b9u);
    let h2 = sg_hash_u32(h1 ^ 0x85ebca6bu);

    // Divide by 2^32 rather than 2^32 - 1 so the result is a half-open [0, 1)
    // range. A closed range would let a feature point land exactly on a cell
    // boundary, where it belongs to two cells at once.
    return vec3<f32>(vec3<u32>(h0, h1, h2)) * (1.0 / 4294967296.0);
}

// SPDX-License-Identifier: MIT OR Apache-2.0
//
// 3D Voronoi / cellular noise, returning the two nearest feature points.
//
// PROVENANCE: written from the published description of Steven Worley's
// cellular texture basis function ("A Cellular Texture Basis Function",
// SIGGRAPH 1996) — scatter one feature point per integer lattice cell, then
// search the neighbouring cells for the nearest few. No shader code was copied
// from any renderer.

struct SgVoronoi {
    f1_distance: f32,
    f1_position: vec3<f32>,
    f2_distance: f32,
    f2_position: vec3<f32>,
}

// Euclidean 3D Voronoi over the unit lattice.
//
// Returns both the nearest (F1) and second-nearest (F2) feature points, in the
// same space as `coord`. Two are returned rather than one because the
// interesting surface properties live in the *relationship* between them:
// `f2_distance - f1_distance` approaches zero exactly on a cell boundary, which
// is what makes it a groove mask, and the direction toward a cell centre is
// what gives an anisotropic surface its brush direction.
//
// `randomness` scales how far each feature point strays from its cell centre.
// At 0 the points sit on a perfect lattice; at 1 they fill their cells. It is
// clamped rather than trusted, because the 3x3x3 search below is only correct
// while every feature point stays inside its own cell — let a point wander
// further and the true nearest neighbour can fall outside the searched
// neighbourhood, producing discontinuities that look like cracks in the
// material and are miserable to diagnose after the fact.
fn sg_voronoi_f1f2_3d(coord: vec3<f32>, randomness: f32) -> SgVoronoi {
    let base = floor(coord);
    let jitter_scale = clamp(randomness, 0.0, 1.0);

    var result: SgVoronoi;
    // Larger than any distance reachable within the searched neighbourhood
    // (which is bounded by the diagonal of a 3x3x3 block), so the first real
    // candidate always wins. Deliberately not f32::MAX: subsequent arithmetic
    // on an unreplaced sentinel would overflow to infinity rather than merely
    // look wrong.
    result.f1_distance = 1e9;
    result.f2_distance = 1e9;
    result.f1_position = coord;
    result.f2_position = coord;

    for (var k: i32 = -1; k <= 1; k++) {
        for (var j: i32 = -1; j <= 1; j++) {
            for (var i: i32 = -1; i <= 1; i++) {
                let cell = base + vec3<f32>(f32(i), f32(j), f32(k));

                // Centre of the cell, displaced by a per-cell random offset in
                // [-0.5, 0.5) scaled by `randomness`. Offsetting from the centre
                // rather than the corner is what makes randomness = 0 produce an
                // even lattice instead of points piled on cell corners.
                let jitter = (sg_hash_cell(cell) - vec3<f32>(0.5)) * jitter_scale;
                let feature = cell + vec3<f32>(0.5) + jitter;

                let d = distance(coord, feature);

                // Insertion into a two-element sorted list. The `else if`
                // matters: without it, a new nearest point would overwrite F1
                // and then immediately be compared against F2 and inserted
                // twice, collapsing F1 and F2 onto the same point and making
                // every boundary-derived value read zero.
                if (d < result.f1_distance) {
                    result.f2_distance = result.f1_distance;
                    result.f2_position = result.f1_position;
                    result.f1_distance = d;
                    result.f1_position = feature;
                } else if (d < result.f2_distance) {
                    result.f2_distance = d;
                    result.f2_position = feature;
                }
            }
        }
    }

    return result;
}

@fragment
fn fragment(in: VertexOutput, @builtin(front_facing) is_front: bool) -> @location(0) vec4<f32> {
    var pbr_input = pbr_input_new();

    let sg_position = in.world_position.xyz;
    let sg_normal = normalize(in.world_normal);
    let sg_view = normalize(view.world_position.xyz - in.world_position.xyz);

    pbr_input.frag_coord = in.position;
    pbr_input.world_position = in.world_position;
    pbr_input.world_normal = sg_normal;
    pbr_input.N = sg_normal;
    pbr_input.V = sg_view;
    // `clip_from_view[3][3] == 1.0` is the documented orthographic test.
    pbr_input.is_orthographic = view.clip_from_view[3][3] == 1.0;

    let n8_param = params.slots[0].x;
    let n9_param = params.slots[1].x;
    let n1_param = params.slots[2].x;
    let n2_vec = (sg_position * n1_param);
    let n3_param = params.slots[3].x;
    let n4_param = params.slots[4].x;
    let n5_voronoi = sg_voronoi_f1f2_3d(n2_vec * n3_param, n4_param);
    let n7_math = (n5_voronoi.f2_distance - n5_voronoi.f1_distance);
    let n10_math = smoothstep(n8_param, n9_param, n7_math);
    let n11_param = params.slots[5];
    let n12_param = params.slots[6];
    let n13_mix = mix(n11_param, n12_param, clamp(n10_math, 0.0, 1.0));
    let n14_param = params.slots[7].x;
    let n15_param = params.slots[8].x;
    let n16_param = params.slots[9].x;
    let n6_vec = (n5_voronoi.f1_position - n2_vec);
    let n17_surface = SgSurface(n13_mix, n14_param, n15_param, 0.5, vec4<f32>(0.0, 0.0, 0.0, 1.0), 1.0, sg_normal, n16_param, n6_vec, 1.0);

    // --- surface properties ---
    pbr_input.material.base_color = n17_surface.base_color;
    pbr_input.material.base_color.a = n17_surface.alpha;
    pbr_input.material.metallic = n17_surface.metallic;
    pbr_input.material.perceptual_roughness = n17_surface.perceptual_roughness;
    pbr_input.material.reflectance = vec3<f32>(n17_surface.reflectance);
    pbr_input.material.emissive = n17_surface.emissive;
    pbr_input.diffuse_occlusion = vec3<f32>(n17_surface.occlusion);
    pbr_input.N = normalize(n17_surface.normal);

    // --- anisotropy ---
    pbr_input.anisotropy_strength = n17_surface.anisotropy_strength;
    let sg_aniso_t = sg_reject_root(n17_surface.anisotropy_tangent, pbr_input.N);
    if (dot(sg_aniso_t, sg_aniso_t) > 1e-12) {
        pbr_input.anisotropy_T = normalize(sg_aniso_t);
        pbr_input.anisotropy_B = normalize(cross(pbr_input.N, pbr_input.anisotropy_T));
    } else {
        pbr_input.anisotropy_strength = 0.0;
    }

    var out = apply_pbr_lighting(pbr_input);
    out = main_pass_post_lighting_processing(pbr_input, out);
    return out;
}
