// GENERATED BY shadergraph — DO NOT EDIT.
//
// Edit the graph and recompile. Any change made here is lost the next time the
// graph is emitted.

#import bevy_pbr::forward_io::VertexOutput
#import bevy_pbr::pbr_types::{PbrInput, pbr_input_new}
#import bevy_pbr::pbr_functions::{apply_pbr_lighting, main_pass_post_lighting_processing}
#import bevy_pbr::mesh_view_bindings::view

// Always emitted, and named apart from the optional `sg_reject` snippet so the
// two never collide: the output node uses this to flatten the anisotropy
// tangent into the surface regardless of what the graph contains.
fn sg_reject_root(a: vec3<f32>, b: vec3<f32>) -> vec3<f32> {
    let denom = dot(b, b);
    if (denom < 1e-12) {
        return a;
    }
    return a - b * (dot(a, b) / denom);
}

struct SgSurface {
    base_color: vec4<f32>,
    metallic: f32,
    perceptual_roughness: f32,
    reflectance: f32,
    emissive: vec4<f32>,
    occlusion: f32,
    normal: vec3<f32>,
    anisotropy_strength: f32,
    anisotropy_tangent: vec3<f32>,
    alpha: f32,
}

struct SgParams {
    slots: array<vec4<f32>, 128>,
}
@group(#{MATERIAL_BIND_GROUP}) @binding(0) var<uniform> params: SgParams;

@group(#{MATERIAL_BIND_GROUP}) @binding(1) var sg_texture_0: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(2) var sg_sampler_0: sampler;

@group(#{MATERIAL_BIND_GROUP}) @binding(3) var sg_texture_1: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(4) var sg_sampler_1: sampler;

@fragment
fn fragment(in: VertexOutput, @builtin(front_facing) is_front: bool) -> @location(0) vec4<f32> {
    var pbr_input = pbr_input_new();

    let sg_position = in.world_position.xyz;
    let sg_normal = normalize(in.world_normal);
    let sg_view = normalize(view.world_position.xyz - in.world_position.xyz);
#ifdef VERTEX_UVS_A
    let sg_uv = vec3<f32>(in.uv, 0.0);
#else
    let sg_uv = vec3<f32>(0.0);
#endif

    pbr_input.frag_coord = in.position;
    pbr_input.world_position = in.world_position;
    pbr_input.world_normal = sg_normal;
    pbr_input.N = sg_normal;
    pbr_input.V = sg_view;
    // `clip_from_view[3][3] == 1.0` is the documented orthographic test.
    pbr_input.is_orthographic = view.clip_from_view[3][3] == 1.0;

    let n2_tex = textureSample(sg_texture_0, sg_sampler_0, (sg_uv).xy);
    let n1_tex = textureSample(sg_texture_1, sg_sampler_1, (sg_uv).xy);
    let n3_mix = mix(n1_tex.rgba, n2_tex.rgba, clamp(n2_tex.a, 0.0, 1.0));
    let n4_surface = SgSurface(n3_mix, 0.0, 0.5, 0.5, vec4<f32>(0.0, 0.0, 0.0, 1.0), 1.0, sg_normal, 0.0, vec3<f32>(0.0), 1.0);

    // --- surface properties ---
    pbr_input.material.base_color = n4_surface.base_color;
    pbr_input.material.base_color.a = n4_surface.alpha;
    pbr_input.material.metallic = n4_surface.metallic;
    pbr_input.material.perceptual_roughness = n4_surface.perceptual_roughness;
    pbr_input.material.reflectance = vec3<f32>(n4_surface.reflectance);
    pbr_input.material.emissive = n4_surface.emissive;
    pbr_input.diffuse_occlusion = vec3<f32>(n4_surface.occlusion);
    pbr_input.N = normalize(n4_surface.normal);

    // --- anisotropy ---
    pbr_input.anisotropy_strength = n4_surface.anisotropy_strength;
    let sg_aniso_t = sg_reject_root(n4_surface.anisotropy_tangent, pbr_input.N);
    if (dot(sg_aniso_t, sg_aniso_t) > 1e-12) {
        pbr_input.anisotropy_T = normalize(sg_aniso_t);
        pbr_input.anisotropy_B = normalize(cross(pbr_input.N, pbr_input.anisotropy_T));
    } else {
        pbr_input.anisotropy_strength = 0.0;
    }

    var out = apply_pbr_lighting(pbr_input);
    out = main_pass_post_lighting_processing(pbr_input, out);
    return out;
}
