// GENERATED BY shadergraph — DO NOT EDIT.
//
// Edit the graph and recompile. Any change made here is lost the next time the
// graph is emitted.

#import bevy_pbr::forward_io::VertexOutput
#import bevy_pbr::pbr_types::{PbrInput, pbr_input_new}
#import bevy_pbr::pbr_functions::{apply_pbr_lighting, main_pass_post_lighting_processing}
#import bevy_pbr::mesh_view_bindings::view

// Always emitted, and named apart from the optional `sg_reject` snippet so the
// two never collide: the output node uses this to flatten the anisotropy
// tangent into the surface regardless of what the graph contains.
fn sg_reject_root(a: vec3<f32>, b: vec3<f32>) -> vec3<f32> {
    let denom = dot(b, b);
    if (denom < 1e-12) {
        return a;
    }
    return a - b * (dot(a, b) / denom);
}

struct SgSurface {
    base_color: vec4<f32>,
    metallic: f32,
    perceptual_roughness: f32,
    reflectance: f32,
    emissive: vec4<f32>,
    occlusion: f32,
    normal: vec3<f32>,
    anisotropy_strength: f32,
    anisotropy_tangent: vec3<f32>,
    alpha: f32,
}

struct SgParams {
    slots: array<vec4<f32>, 128>,
}
@group(#{MATERIAL_BIND_GROUP}) @binding(0) var<uniform> params: SgParams;

// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Integer avalanche hashing for procedural noise.
//
// PROVENANCE: written from published descriptions of multiply-xorshift bit
// mixing. The xorshift/multiply/xorshift construction is the standard shape of
// an integer finaliser (the same form as SplitMix's finaliser and Wang's
// integer hash); the specific constants are the `lowbias32` pair from Chris
// Wellons' "Prospecting for Hash Functions", which the author released into the
// public domain. No shader code was copied from any renderer.

// Avalanche a single 32-bit integer.
//
// Three rounds, each an xor-with-right-shift followed by an odd-constant
// multiply. The xorshift moves entropy from the high bits (where multiplication
// concentrates it) back down into the low bits; the multiply then spreads it up
// again. Two full rounds plus a final xorshift is the minimum that passes
// avalanche testing — one round leaves the lowest bits visibly correlated,
// which in a Voronoi shows up as feature points aligning on faint grid lines.
fn sg_hash_u32(x_in: u32) -> u32 {
    var x = x_in;
    x ^= x >> 16u;
    x *= 0x7feb352du;
    x ^= x >> 15u;
    x *= 0x846ca68bu;
    x ^= x >> 16u;
    return x;
}

// Hash an integer lattice cell to three independent values in [0, 1).
//
// The cell coordinate arrives as a float because it came from `floor()`, and is
// bitcast through a signed integer rather than converted directly to `u32`:
// negative cells are ordinary (any surface at negative world coordinates lives
// in them), and `u32(-1.0)` is undefined in WGSL whereas `i32(-1.0)` is not.
//
// The three channels are decorrelated by re-hashing with distinct odd constants
// rather than by hashing three different tuples, which costs two extra rounds
// instead of two extra full hashes. The constants are the golden-ratio and
// SplitMix increments — any odd values with well-spread bits would do; these
// are conventional and easy to recognise.
fn sg_hash_cell(cell: vec3<f32>) -> vec3<f32> {
    let c = bitcast<vec3<u32>>(vec3<i32>(cell));

    // Fold the three axes into one value first, so that swapping two
    // coordinates gives an unrelated result. Hashing each axis separately and
    // summing would make the field symmetric about the diagonal — a subtle
    // artifact that is very visible on flat panels.
    let h0 = sg_hash_u32(c.x ^ sg_hash_u32(c.y ^ sg_hash_u32(c.z)));
    let h1 = sg_hash_u32(h0 ^ 0x9e3779b9u);
    let h2 = sg_hash_u32(h1 ^ 0x85ebca6bu);

    // Divide by 2^32 rather than 2^32 - 1 so the result is a half-open [0, 1)
    // range. A closed range would let a feature point land exactly on a cell
    // boundary, where it belongs to two cells at once.
    return vec3<f32>(vec3<u32>(h0, h1, h2)) * (1.0 / 4294967296.0);
}

// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Perlin gradient noise, and the per-octave weighting both fBm variants share.
//
// PROVENANCE: written from Ken Perlin's published description of gradient noise
// (1985, and the 2002 "Improving Noise" revision that introduced the quintic
// fade). No shader code was copied from any renderer: Cycles serves only as a
// correctness reference (compare rendered output), never as a source, because
// copying its Apache-2.0 code would sink this crate's MIT half.

// Largest number of octaves either fBm path will evaluate.
//
// NOTE: Mirrored by `node::MAX_NOISE_OCTAVES` on the Rust side, which bounds the
// unrolled variant's octave count. `the_octave_cap_agrees_across_the_language_boundary`
// pins the two together; a silent disagreement would mean the unrolled node
// generating more octaves than the dynamic one can reach, so the two would stop
// being comparable — which is the entire reason both exist.
const SG_MAX_OCTAVES: i32 = 8;

// A pseudo-random unit vector for one lattice cell.
//
// The hash gives three values in [0,1); those map to a point in the [-1,1] cube
// and are then normalised onto the sphere.
//
// NOTE: Normalising a uniform cube sample is very slightly biased toward the cube's
// corners — the eight diagonal directions are marginally more likely than the
// axial ones. Perlin's 2002 revision avoids this by picking from twelve fixed
// gradients on the cube's edges. That is measurably better for noise examined on
// its own and invisible under the kind of layered grunge this is for, so the
// cheaper form is used deliberately rather than by oversight. If a directional
// artifact ever does show up on a flat panel, the twelve-gradient set is the fix.
fn sg_gradient(cell: vec3<f32>) -> vec3<f32> {
    let h = sg_hash_cell(cell) * 2.0 - 1.0;
    let len2 = dot(h, h);
    // A cell whose hash lands almost exactly at the cube centre would normalise
    // to NaN and put a black speck on the surface. Vanishingly unlikely and
    // trivially cheap to exclude.
    if (len2 < 1e-8) {
        return vec3<f32>(0.0, 0.0, 1.0);
    }
    return h * inverseSqrt(len2);
}

// Gradient noise at a point, in roughly [-1, 1].
fn sg_perlin_3d(p: vec3<f32>) -> f32 {
    let cell = floor(p);
    let f = p - cell;

    // KEY: Perlin's quintic fade: 6t^5 - 15t^4 + 10t^3. This is the SAME polynomial
    // as `RampInterp::QuinticEase` in the color ramp, and for the same reason —
    // it is the quintic Hermite segment with zero velocity AND zero acceleration
    // at both ends. Cubic smoothstep would do here too, but its second derivative
    // is discontinuous at the lattice, which shows up as faint grid lines once
    // the noise drives a normal.
    let u = f * f * f * (f * (f * 6.0 - 15.0) + 10.0);

    // Dot each corner's gradient with the offset from that corner to the point.
    let g000 = dot(sg_gradient(cell + vec3<f32>(0.0, 0.0, 0.0)), f - vec3<f32>(0.0, 0.0, 0.0));
    let g100 = dot(sg_gradient(cell + vec3<f32>(1.0, 0.0, 0.0)), f - vec3<f32>(1.0, 0.0, 0.0));
    let g010 = dot(sg_gradient(cell + vec3<f32>(0.0, 1.0, 0.0)), f - vec3<f32>(0.0, 1.0, 0.0));
    let g110 = dot(sg_gradient(cell + vec3<f32>(1.0, 1.0, 0.0)), f - vec3<f32>(1.0, 1.0, 0.0));
    let g001 = dot(sg_gradient(cell + vec3<f32>(0.0, 0.0, 1.0)), f - vec3<f32>(0.0, 0.0, 1.0));
    let g101 = dot(sg_gradient(cell + vec3<f32>(1.0, 0.0, 1.0)), f - vec3<f32>(1.0, 0.0, 1.0));
    let g011 = dot(sg_gradient(cell + vec3<f32>(0.0, 1.0, 1.0)), f - vec3<f32>(0.0, 1.0, 1.0));
    let g111 = dot(sg_gradient(cell + vec3<f32>(1.0, 1.0, 1.0)), f - vec3<f32>(1.0, 1.0, 1.0));

    // Trilinear blend along the faded axes.
    let x00 = mix(g000, g100, u.x);
    let x10 = mix(g010, g110, u.x);
    let x01 = mix(g001, g101, u.x);
    let x11 = mix(g011, g111, u.x);
    let y0 = mix(x00, x10, u.y);
    let y1 = mix(x01, x11, u.y);

    // 3D gradient noise with unit gradients peaks near sqrt(3)/2 ~= 0.866, not
    // 1.0. Scaling by its reciprocal makes the output span [-1, 1] so that
    // `roughness` behaves the same here as it would for any other basis.
    return mix(y0, y1, u.z) * 1.1547005;
}

// How much octave `octave` contributes at a given `detail`.
//
// KEY: Shared by BOTH fBm variants — the dynamic loop calls it per iteration and
// the unrolled generator calls it per unrolled step. That sharing is not tidiness:
// it is what makes the two provably the same function, so switching between them
// compares a dynamic loop against straight-line code and nothing else.
//
// Octave 0 is always full. Each subsequent octave fades in over one unit of
// detail, so `detail` is continuous rather than a step count — dragging it does
// not pop an octave into existence.
fn sg_octave_weight(detail: f32, octave: i32) -> f32 {
    return clamp(detail - f32(octave) + 1.0, 0.0, 1.0);
}

// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Fractal Brownian motion over Perlin noise, with a runtime octave count.
//
// Only the LIVE variant of the noise node pulls this in. The unrolled variant
// generates its own straight-line equivalent per node — see `NoiseOctaves`.

// Sum octaves of gradient noise, output remapped to [0, 1].
//
// The loop bound is `detail`, which arrives from a uniform slot, so dragging the
// detail slider is a buffer write rather than a recompile. That is the whole
// point of this variant, and it is not free: a loop whose trip count the shader
// compiler cannot see is harder to optimise than an unrolled one.
//
// The `break` matters more than it looks. Weights fall to zero once the octave
// index passes `detail`, so a graph running at detail 2 does three iterations,
// not eight — which means this is often FASTER than an unrolled node capped at
// eight, despite the dynamic bound. Worth measuring rather than assuming.
fn sg_fbm_3d(p: vec3<f32>, detail: f32, roughness: f32, lacunarity: f32) -> f32 {
    var sum = 0.0;
    var norm = 0.0;
    var amp = 1.0;
    var freq = 1.0;

    for (var i = 0; i < SG_MAX_OCTAVES; i = i + 1) {
        let w = amp * sg_octave_weight(detail, i);
        if (w <= 0.0) {
            break;
        }
        sum = sum + w * sg_perlin_3d(p * freq);
        norm = norm + w;
        amp = amp * roughness;
        freq = freq * lacunarity;
    }

    // Normalising by the accumulated weight rather than by a closed form keeps
    // the output range stable as `roughness` changes. Without it, a low
    // roughness would make the result hug 0.5 and a high one would blow past
    // the range, so the two controls would not be independent.
    if (norm <= 0.0) {
        return 0.5;
    }
    return sum / norm * 0.5 + 0.5;
}

// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Vector decomposition helpers. Textbook linear algebra; no external source.

// The component of `a` that lies along `b`.
//
// Guards against a degenerate `b`: `dot(b, b)` is zero for a zero-length
// vector, and dividing by it yields NaN. A NaN here does not stay local — it
// propagates through the brush direction into the anisotropy tangent and
// finally into the lit color, where it renders as a black or garbage fragment
// with nothing pointing back at the division that caused it.
fn sg_project(a: vec3<f32>, b: vec3<f32>) -> vec3<f32> {
    let denom = dot(b, b);
    if (denom < 1e-12) {
        return vec3<f32>(0.0);
    }
    return b * (dot(a, b) / denom);
}

// The component of `a` perpendicular to `b`.
//
// This is the operation that flattens an arbitrary direction into a surface:
// pass a surface normal as `b` and whatever remains is tangent to the surface.
// Blender has no such node and expects Project followed by Subtract.
fn sg_reject(a: vec3<f32>, b: vec3<f32>) -> vec3<f32> {
    return a - sg_project(a, b);
}

// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Blending two evaluated surfaces.
//
// WHY THIS IS POSSIBLE HERE AND NOT IN BLENDER: a Blender `Shader` socket holds
// a closure — a BSDF that has not been evaluated — so mixing two of them means
// mixing two *functions*, which is why Cycles needs a whole closure system to do
// it and why it cannot be lowered to a fixed structure. `SgSurface` is a struct
// of numbers that has already been evaluated, so mixing two surfaces is ten
// lerps and nothing else.
//
// NOTE: COST: there is no branch here, and there cannot be one. Both surfaces are
// fully evaluated at every fragment before either is used, so a two-layer
// material costs both layers everywhere — not the cheaper one where the mask
// says so. Nesting these for a third layer adds a third. Blender behaves the
// same way; it is worth knowing before layering six of them.

// Lerp two surfaces.
//
// `factor` is clamped rather than trusted. WGSL's `mix` EXTRAPOLATES outside
// [0,1] — a factor of 1.4 does not saturate at surface B, it overshoots past it,
// producing out-of-gamut colors and negative roughness. Every other mix node in
// this compiler clamps for the same reason.
fn sg_mix_surface(factor: f32, a: SgSurface, b: SgSurface) -> SgSurface {
    let t = clamp(factor, 0.0, 1.0);

    var out: SgSurface;
    out.base_color = mix(a.base_color, b.base_color, t);
    out.metallic = mix(a.metallic, b.metallic, t);
    out.perceptual_roughness = mix(a.perceptual_roughness, b.perceptual_roughness, t);
    out.reflectance = mix(a.reflectance, b.reflectance, t);
    out.emissive = mix(a.emissive, b.emissive, t);
    out.occlusion = mix(a.occlusion, b.occlusion, t);

    // NOTE: A lerp of two directions is not a rotation between them: it cuts the
    // chord rather than following the arc, and shortens as the two diverge.
    // Left un-normalised HERE on purpose — the output block normalises the
    // normal it is given, unconditionally, so normalising again would be dead
    // work at every fragment. The direction is right; only the length is not,
    // and nothing between here and there reads the length.
    out.normal = mix(a.normal, b.normal, t);

    out.anisotropy_strength = mix(a.anisotropy_strength, b.anisotropy_strength, t);
    // Same story as the normal, and the output block gives this one the same
    // treatment: it is rejected against the shading normal and re-normalised,
    // with the strength forced to zero if the result is degenerate. So a lerp
    // that passes exactly through zero midway between two opposed tangents
    // fails safe rather than producing NaN.
    out.anisotropy_tangent = mix(a.anisotropy_tangent, b.anisotropy_tangent, t);

    out.alpha = mix(a.alpha, b.alpha, t);
    return out;
}

@fragment
fn fragment(in: VertexOutput, @builtin(front_facing) is_front: bool) -> @location(0) vec4<f32> {
    var pbr_input = pbr_input_new();

    let sg_position = in.world_position.xyz;
    let sg_normal = normalize(in.world_normal);
    let sg_view = normalize(view.world_position.xyz - in.world_position.xyz);

    pbr_input.frag_coord = in.position;
    pbr_input.world_position = in.world_position;
    pbr_input.world_normal = sg_normal;
    pbr_input.N = sg_normal;
    pbr_input.V = sg_view;
    // `clip_from_view[3][3] == 1.0` is the documented orthographic test.
    pbr_input.is_orthographic = view.clip_from_view[3][3] == 1.0;

    let n1_param = params.slots[0].x;
    let n2_vec = (sg_position * n1_param);
    let n3_noise = sg_fbm_3d(n2_vec * 5.0, 2.0, 0.5, 2.0);
    let n4_math = smoothstep(n3_noise, 0.5, 0.5);
    let n5_param = params.slots[1].x;
    let n6_math = (n4_math * n5_param);
    let n7_param = params.slots[2];
    let n8_param = params.slots[3].x;
    let n9_surface = SgSurface(n7_param, 0.0, n8_param, 0.5, vec4<f32>(0.0, 0.0, 0.0, 1.0), 1.0, sg_normal, 0.0, vec3<f32>(0.0), 1.0);
    let n12_param = params.slots[4];
    let n13_param = params.slots[5].x;
    let n14_param = params.slots[6].x;
    let n15_param = params.slots[7].x;
    let n10_param = params.slots[8].xyz;
    let n11_vec = sg_reject(n10_param, sg_normal);
    let n16_surface = SgSurface(n12_param, n13_param, n14_param, 0.5, vec4<f32>(0.0, 0.0, 0.0, 1.0), 1.0, sg_normal, n15_param, n11_vec, 1.0);
    let n17_mixsurf = sg_mix_surface(n6_math, n9_surface, n16_surface);

    // --- surface properties ---
    pbr_input.material.base_color = n17_mixsurf.base_color;
    pbr_input.material.base_color.a = n17_mixsurf.alpha;
    pbr_input.material.metallic = n17_mixsurf.metallic;
    pbr_input.material.perceptual_roughness = n17_mixsurf.perceptual_roughness;
    pbr_input.material.reflectance = vec3<f32>(n17_mixsurf.reflectance);
    pbr_input.material.emissive = n17_mixsurf.emissive;
    pbr_input.diffuse_occlusion = vec3<f32>(n17_mixsurf.occlusion);
    pbr_input.N = normalize(n17_mixsurf.normal);

    // --- anisotropy ---
    pbr_input.anisotropy_strength = n17_mixsurf.anisotropy_strength;
    let sg_aniso_t = sg_reject_root(n17_mixsurf.anisotropy_tangent, pbr_input.N);
    if (dot(sg_aniso_t, sg_aniso_t) > 1e-12) {
        pbr_input.anisotropy_T = normalize(sg_aniso_t);
        pbr_input.anisotropy_B = normalize(cross(pbr_input.N, pbr_input.anisotropy_T));
    } else {
        pbr_input.anisotropy_strength = 0.0;
    }

    var out = apply_pbr_lighting(pbr_input);
    out = main_pass_post_lighting_processing(pbr_input, out);
    return out;
}
